export default {
	/** SCHOLARSHIPS */
	GET_SCHOLARSHIPS_PENDING: 'GET_SCHOLARSHIPS_PENDING',
	GET_SCHOLARSHIPS_FULFILLED: 'GET_SCHOLARSHIPS_FULFILLED',
	GET_SCHOLARSHIPS_REJECTED: 'GET_SCHOLARSHIPS_REJECTED',
	/** FAVORITE SCHOLARSHIPS */
	SET_FAVORITE_SCHOLARSHIPS_FULFILLED: 'SET_FAVORITE_SCHOLARSHIPS_FULFILLED'
};